#!/bin/bash
#Keep this file in secret place. Never commit it!!! Never share it!!!
#Make sure that this file has not read/write/execute permissions:
#     chmod 000 secret-config
MASTER_KEY="FUCK1heB0x3100"
USER="dimhold"
ALGORITHM="sha1sum"
DELIMETER="."

get_master_key() {
	echo $MASTER_KEY
}

get_user() {
	echo $USER
}

get_hash_algorithm() {
	echo $ALGORITHM
}

get_delimeter() {
	echo $DELIMETER
}
